version: '3.8'
services:
  refine:
    container_name: vietedu-refine
    build: .
    ports:
      - "3580:3000"  # Chuyển từ 3000 sang 3002
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:1317
      - NEXT_PUBLIC_NODEINFO_URL=http://localhost:1318
      - NODE_ID=node1
